using Project_PTTK.Business;
using Project_PTTK.DataAccess.Phieu;
using Project_PTTK.DataAccess;
using Project_PTTK.Model;
using System.Security.AccessControl;

namespace Project_PTTK
{
    public partial class MH_TAOPHIEUGIAHAN : Form
    {
        private PhieuGiaHanBUS phieuGiaHanBUS = new PhieuGiaHanBUS(new PhieuGiaHanDAO(), new PhieuDangKyDAO());
        private PhieuDangKyBUS phieuDangKyBUS = new PhieuDangKyBUS();
        private KhachHangBUS khachHangBUS = new KhachHangBUS();
        private DichVuBUS dichVuBUS = new DichVuBUS(new DichVuDAO());
        public MH_TAOPHIEUGIAHAN()
        {
            InitializeComponent();
        }

        private void MH_TAOPHIEUGIAHAN_Load(object sender, EventArgs e)
        {

        }

        private void txtMaPhieu_TextChanged(object sender, EventArgs e)
        {
            var phieuDangKy = phieuDangKyBUS.LayTheoMa(int.Parse(txtMaPhieu.Text));
            if (phieuDangKy != null)
            {
                txtTenKH.Text = phieuDangKy.MaKH.ToString();
            }
            dgvDichVuDaDK.DataSource = dichVuBUS.LayDanhSach();
        }

        private void dgvDichVuDaDK_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }

        private void btnChonDichVu_Click(object sender, EventArgs e)
        {
            if (dgvDichVuDaDK.SelectedRows.Count > 0)
            {
                DataGridViewRow selectedRow = dgvDichVuDaDK.SelectedRows[0];

                DichVu selectedService = new DichVu
                {
                    MaDichVu = Convert.ToInt32(selectedRow.Cells["MaDichVu"].Value),
                    TenDichVu = selectedRow.Cells["TenDichVu"].Value.ToString(),
                };
            }
        }

        private void dgvLichThiMoi_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }

        private void btnTaoPhieuGiaHan_Click(object sender, EventArgs e)
        {
            if (dgvLichThiMoi.SelectedRows.Count > 0)
            {
                DataGridViewRow selectedRow = dgvLichThiMoi.SelectedRows[0];
                PhieuGiaHan phieuGiaHan = new PhieuGiaHan
                {
                    MaPhieuDangKy = int.Parse(txtMaPhieu.Text),
                    NgayTao = DateOnly.FromDateTime(DateTime.Now),
                    LyDo = cmbLyDo.Text,
                    TrangThaiThanhToan = "Chưa thanh toán",
                    MaPhieuGiaHan = 0 // Assuming this is auto-generated by the database
                };
                phieuGiaHanBUS.TaoPhieu(phieuGiaHan); // Use the instance of PhieuGiaHanBUS instead of referencing it statically
                MessageBox.Show("Tạo phiếu gia hạn thành công!");
            }
            else
            {
                MessageBox.Show("Vui lòng chọn lịch thi để tạo phiếu gia hạn.");
            }
        }
    }
}
